### ISSUE TITLE
Contact / suggestions pour la plateforme ?

### ISSUE THREAD

**Issue by mnoblecourt** [jlm2017/volunteers#5]
Bonjour,

Merci beaucoup pour le lancement de votre blog qui permet aux simples militants (d'autant plus provinciaux) comme moi de comprendre ce qui se passe derrière la machine.
Je n'ai pas trouvé de moyen de vous contacter pour faire remonter des suggestions d'extensions de la plateforme, je le fais donc ici (pas de souci si vous préférez passer en discussion email et supprimer cette Issue). De ce que je vois au niveau de mon groupe d'appui (et des autres groupes du département), les besoins idéaux sont les suivants :

 - un système d'échange (type forum/Slack) simple et universel, organisable par sujet, au niveau du GA et au-delà p. ex. sur des thématiques
- un système de partage/stockage de fichiers (compte rendus, documents de travail, vidéos, etc.) au niveau du GA et/ou au delà (partage possible entre utilisateurs/GA)
- une possibilité de vote en ligne sécurisée au niveau du GA et/ou au dela (p. ex. à l'échelle d'une circonscription)
- un outil d'annuaire permettant de visualiser les membres, la composition des groupes, etc. (apparemment on devrait pouvoir voir les autres membres prochainement)

J'imagine qu'une partie de cela a été discuté à Marseille (je n'ai malheureusement pu être là) et/ou est déjà dans vos plans, je me permets néanmoins d'apporter mon grain de sel. L'idéal serait bien sûr de connecter à la plateforme des outils existants (Mattermost, nextcloud...) pour éviter des login différents.
En l'occurrence dans mon GA on est (re)partis sur des outils ad hoc (un Framagroup remplaçant un Google group) mais je ne suis pas très optimiste sur leur durabilité si ça n'est pas intégré à un outil global.
Je ne suis malheureusement pas développeur mais à votre disposition pour en discuter et beta tester :)
Merci pour tout ce que vous faites !

**Comment by jillro** [comment]
Bonjour !

Merci de tes suggestions :) Elles auraient cependant plus leur place dans [la boite à idées](https://lafranceinsoumise.fr/2017/08/16/convention-nationale-de-france-insoumise-lancement-de-boite-a-idees/), ceci étant plutôt un lieu destiné à l'organisation du travail des développeurs. Une synthèse sera faite de la boîte à idée permettant de déterminer les chantiers principaux. Je me permets donc de clore le ticket.

Bonne journée !
