### ISSUE TITLE
Gestion des comptes lors des évènements

### ISSUE THREAD

**Issue by hjurin** [jlm2017/volunteers#6]
Bonjour,

Je me permets d'écrire le ticket en français.
Depuis que je soutiens la candidature sur le site j'ai remarqué que la gestion des comptes côté client était assez minime. 

Encore récemment, vu que j'ai été tiré au sort pour la convention, j'ai du ressaisir l'ensemble de mes informations alors que tout ça devrait être déjà saisi quelque part.

Je ne vois pas d'interface claire de connexion sur le site alors que j'ai bien un compte.

Je pense que ce serait vraiment utile pour les insoumis de pouvoir gérer son compte sur le site facilement, avec une gestion des moyens de paiement par exemple, un profil insoumis etc. Pour les insoumis branchés digital, ça pourrait aider !

**Comment by jillro** [comment]
Bonjour,

Les comptes agir.lafranceinsoumise.fr disposent déjà d'une gestion de profil assez poussée.

Effectivement le site matériel n'est pas encore totalement intégré avec le reste de la plateforme. C'est un point à améliorer mais pas une priorité.

Il y a un bouton "se connecter" sur la page d'accueil de lafranceinsoumise.fr.
